import operator
from typing import Annotated, Any, Dict, List, Optional, TypedDict, Union
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    """
    The 'Brain' of the AI Agent.
    
    This state is passed between nodes in the LangGraph.
    It persists the conversation history, the analysis of the user's intent,
    and the intermediate results of any mechanical resolutions (dice rolls).
    """
    
    # --- Conversation History ---
    # We use 'operator.add' to append new messages to the history 
    # rather than overwriting the list each step.
    messages: Annotated[List[BaseMessage], operator.add]
    
    # --- Context Snapshot ---
    # Data from the Hybrid ECS, injected at the start of the turn.
    # We don't modify the DB directly here; we just read this snapshot.
    player_entity: Dict[str, Any]
    nearby_entities: List[Dict[str, Any]]
    current_zone: Dict[str, Any]
    
    # --- Reasoning Pipeline ---
    # 1. Router Analysis
    intent: Optional[str]  # e.g., "COMBAT", "NAVIGATION", "TALK", "SYSTEM"
    reasoning_log: List[str] # Debug log for the client console
    
    # 2. Tool/Mechanics Execution
    # If the Router decides we need mechanics (e.g., an attack roll),
    # the tool calls are stored here.
    pending_tool_calls: List[Dict[str, Any]]
    
    # 3. Mechanics Results
    # The output of the deterministic engine (e.g., "Roll: 18 vs AC 14 -> Hit")
    mechanics_results: List[str]
    
    # --- Final Output ---
    # The final narrative text generated by the Narrator node.
    final_response: Optional[str]